highlighter: rouge
paginate: 10
markdown: kramdown
host: 0.0.0.0

subscribe_rss: /atom.xml
kramdown:
  input: GFM
  hard_wrap: false

home_url: "https://tech.lemoncloud.io/"
representing_image: "/images/lemon-emblem.png"
twitter_image: ""

sass:
    sass_dir: css

trawler_mode: true
gems: [jekyll-paginate]
future: true
